package operApp;


/**
* operApp/oper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from oper.idl
* Tuesday, 23 April, 2019 1:15:50 AM IST
*/

public interface oper extends operOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface oper
