package operApp;


/**
* operApp/operOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from oper.idl
* Tuesday, 23 April, 2019 1:15:50 AM IST
*/

public interface operOperations 
{

  // float add(in float num1, in float num2);
  String datetime ();
  void shutdown ();
} // interface operOperations
