package operApp;

/**
* operApp/operHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from oper.idl
* Tuesday, 23 April, 2019 1:15:50 AM IST
*/

public final class operHolder implements org.omg.CORBA.portable.Streamable
{
  public operApp.oper value = null;

  public operHolder ()
  {
  }

  public operHolder (operApp.oper initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = operApp.operHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    operApp.operHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return operApp.operHelper.type ();
  }

}
